In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import os
from kaggle_secrets import UserSecretsClient

# Fetch the token securely from Kaggle Secrets
try:
    os.environ["HF_TOKEN"] = UserSecretsClient().get_secret("HF_TOKEN")
    print("Hugging Face token successfully loaded!")
except Exception as e:
    print("Could not load Hugging Face token. Check your Kaggle Secrets.")

Hugging Face token successfully loaded!

In [3]:
from datasets import load_dataset

ds = load_dataset("ai4privacy/pii-masking-300k")

README.md:   0%|          | 0.00/17.1k [00:00<?, ?B/s]

data/train/1english_openpii_30k.jsonl: reconstructing file:   0%|          |  0.00B /  103MB

data/train/1english_openpii_30k.jsonl: downloading bytes:           |  0.00B

data/train/dutch_openpii_28k.jsonl: reconstructing file:   0%|          |  0.00B /  102MB

data/train/dutch_openpii_28k.jsonl: downloading bytes:           |  0.00B

data/train/french_openpii_31k.jsonl: reconstructing file:   0%|          |  0.00B /  114MB

data/train/french_openpii_31k.jsonl: downloading bytes:           |  0.00B

data/train/german_openpii_30k.jsonl: reconstructing file:   0%|          |  0.00B /  108MB

data/train/german_openpii_30k.jsonl: downloading bytes:           |  0.00B

data/train/italian_openpii_29k.jsonl: reconstructing file:   0%|          |  0.00B /  104MB

data/train/italian_openpii_29k.jsonl: downloading bytes:           |  0.00B

data/train/spanish_openpii_29k.jsonl: reconstructing file:   0%|          |  0.00B /  102MB

data/train/spanish_openpii_29k.jsonl: downloading bytes:           |  0.00B

data/validation/1english_openpii_8k.json(…): reconstructing file:   0%|          |  0.00B / 27.3MB

data/validation/1english_openpii_8k.json(…): downloading bytes:           |  0.00B

data/validation/dutch_openpii_7k.jsonl: reconstructing file:   0%|          |  0.00B / 27.0MB

data/validation/dutch_openpii_7k.jsonl: downloading bytes:           |  0.00B

data/validation/french_openpii_8k.jsonl: reconstructing file:   0%|          |  0.00B / 30.7MB

data/validation/french_openpii_8k.jsonl: downloading bytes:           |  0.00B

data/validation/german_openpii_8k.jsonl: reconstructing file:   0%|          |  0.00B / 29.2MB

data/validation/german_openpii_8k.jsonl: downloading bytes:           |  0.00B

data/validation/italian_openpiii_8k.json(…): reconstructing file:   0%|          |  0.00B / 28.3MB

data/validation/italian_openpiii_8k.json(…): downloading bytes:           |  0.00B

data/validation/spanish_openpii_8k.jsonl: reconstructing file:   0%|          |  0.00B / 27.7MB

data/validation/spanish_openpii_8k.jsonl: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/177677 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/47728 [00:00<?, ? examples/s]

In [4]:
ds

DatasetDict({
    train: Dataset({
        features: ['source_text', 'target_text', 'privacy_mask', 'span_labels', 'mbert_text_tokens', 'mbert_bio_labels', 'id', 'language', 'set'],
        num_rows: 177677
    })
    validation: Dataset({
        features: ['source_text', 'target_text', 'privacy_mask', 'span_labels', 'mbert_text_tokens', 'mbert_bio_labels', 'id', 'language', 'set'],
        num_rows: 47728
    })
})

In [5]:
train_df = pd.DataFrame(ds['train'])

In [6]:
valid_df = pd.DataFrame(ds['validation'])
valid_df.head()

,source_text,target_text,privacy_mask,span_labels,mbert_text_tokens,mbert_bio_labels,id,language,set
0,On the video sharing platform for educational ...,On the video sharing platform for educational ...,"[{'value': 'paaltwvkjuijwbj957', 'start': 165,...","[[316, 320, ""USERNAME""], [254, 272, ""USERNAME""...","[On, the, video, sharing, platform, for, educa...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",40770A,English,validation
1,d wsfdkmi9214 shared personal experiences rela...,d [USERNAME] shared personal experiences relat...,"[{'value': 'wsfdkmi9214', 'start': 2, 'end': 1...","[[355, 356, ""USERNAME""], [339, 350, ""USERNAME""...","[d, w, ##s, ##f, ##d, ##km, ##i, ##9, ##21, ##...","[O, B-USERNAME, I-USERNAME, I-USERNAME, I-USER...",40770B,English,validation
2,ach other respectfully in their comments. yega...,ach other respectfully in their comments. [USE...,"[{'value': 'yeganeh-afchar', 'start': 42, 'end...","[[339, 344, ""TIME""], [61, 74, ""USERNAME""], [42...","[ach, other, respect, ##fully, in, their, comm...","[O, O, O, O, O, O, O, O, B-USERNAME, I-USERNAM...",40770C,English,validation
3,"{\n ""Guidelines"": {\n ""maximumAge"": ""May 5...","{\n ""Guidelines"": {\n ""maximumAge"": ""[BOD]...","[{'value': 'May 5th, 1966', 'start': 39, 'end'...","[[432, 441, ""IDCARD""], [391, 400, ""IDCARD""], [...","[{, "", Guide, ##lines, "", :, {, "", maximum, ##...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",40771,English,validation
4,Subject: Collaboration Opportunity in Online C...,Subject: Collaboration Opportunity in Online C...,[],[],"[Sub, ##ject, :, Coll, ##aboration, Op, ##port...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",40779A,English,validation

In [7]:
# train_df = train_df.drop(columns='set')
valid_df = valid_df.drop(columns='set')
valid_df.head()

,source_text,target_text,privacy_mask,span_labels,mbert_text_tokens,mbert_bio_labels,id,language
0,On the video sharing platform for educational ...,On the video sharing platform for educational ...,"[{'value': 'paaltwvkjuijwbj957', 'start': 165,...","[[316, 320, ""USERNAME""], [254, 272, ""USERNAME""...","[On, the, video, sharing, platform, for, educa...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",40770A,English
1,d wsfdkmi9214 shared personal experiences rela...,d [USERNAME] shared personal experiences relat...,"[{'value': 'wsfdkmi9214', 'start': 2, 'end': 1...","[[355, 356, ""USERNAME""], [339, 350, ""USERNAME""...","[d, w, ##s, ##f, ##d, ##km, ##i, ##9, ##21, ##...","[O, B-USERNAME, I-USERNAME, I-USERNAME, I-USER...",40770B,English
2,ach other respectfully in their comments. yega...,ach other respectfully in their comments. [USE...,"[{'value': 'yeganeh-afchar', 'start': 42, 'end...","[[339, 344, ""TIME""], [61, 74, ""USERNAME""], [42...","[ach, other, respect, ##fully, in, their, comm...","[O, O, O, O, O, O, O, O, B-USERNAME, I-USERNAM...",40770C,English
3,"{\n ""Guidelines"": {\n ""maximumAge"": ""May 5...","{\n ""Guidelines"": {\n ""maximumAge"": ""[BOD]...","[{'value': 'May 5th, 1966', 'start': 39, 'end'...","[[432, 441, ""IDCARD""], [391, 400, ""IDCARD""], [...","[{, "", Guide, ##lines, "", :, {, "", maximum, ##...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",40771,English
4,Subject: Collaboration Opportunity in Online C...,Subject: Collaboration Opportunity in Online C...,[],[],"[Sub, ##ject, :, Coll, ##aboration, Op, ##port...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...",40779A,English

In [8]:
train_df = train_df[train_df['language'] == 'English']
valid_df = valid_df[valid_df['language'] == 'English']
len(train_df)

29908

In [9]:
unique_labels = []
for bio_lst in train_df['mbert_bio_labels']:
    for bio_label in bio_lst:
        if bio_label not in unique_labels:
            unique_labels.append(bio_label)
unique_labels

['O',
 'B-USERNAME',
 'I-USERNAME',
 'B-TIME',
 'I-TIME',
 'B-DATE',
 'I-DATE',
 'B-LASTNAME1',
 'I-LASTNAME1',
 'B-LASTNAME2',
 'I-LASTNAME2',
 'B-EMAIL',
 'I-EMAIL',
 'B-SOCIALNUMBER',
 'I-SOCIALNUMBER',
 'B-IDCARD',
 'I-IDCARD',
 'B-COUNTRY',
 'B-BUILDING',
 'B-STREET',
 'I-STREET',
 'B-CITY',
 'B-STATE',
 'I-STATE',
 'B-POSTCODE',
 'I-POSTCODE',
 'B-PASS',
 'I-PASS',
 'I-COUNTRY',
 'I-CITY',
 'B-PASSPORT',
 'I-PASSPORT',
 'B-TEL',
 'I-TEL',
 'B-DRIVERLICENSE',
 'I-DRIVERLICENSE',
 'B-BOD',
 'I-BOD',
 'B-SEX',
 'B-IP',
 'I-IP',
 'I-SEX',
 'I-BUILDING',
 'B-SECADDRESS',
 'I-SECADDRESS',
 'B-LASTNAME3',
 'I-LASTNAME3',
 'B-GIVENNAME1',
 'I-GIVENNAME1',
 'B-GIVENNAME2',
 'I-GIVENNAME2',
 'B-TITLE',
 'I-TITLE',
 'B-GEOCOORD',
 'I-GEOCOORD',
 'B-CARDISSUER',
 'I-CARDISSUER']

# Create bidirectional mapping

In [10]:
label2id = {label: idx for idx, label in enumerate(unique_labels)}
id2label = {idx: label for label, idx in label2id.items()}
id2label

{0: 'O',
 1: 'B-USERNAME',
 2: 'I-USERNAME',
 3: 'B-TIME',
 4: 'I-TIME',
 5: 'B-DATE',
 6: 'I-DATE',
 7: 'B-LASTNAME1',
 8: 'I-LASTNAME1',
 9: 'B-LASTNAME2',
 10: 'I-LASTNAME2',
 11: 'B-EMAIL',
 12: 'I-EMAIL',
 13: 'B-SOCIALNUMBER',
 14: 'I-SOCIALNUMBER',
 15: 'B-IDCARD',
 16: 'I-IDCARD',
 17: 'B-COUNTRY',
 18: 'B-BUILDING',
 19: 'B-STREET',
 20: 'I-STREET',
 21: 'B-CITY',
 22: 'B-STATE',
 23: 'I-STATE',
 24: 'B-POSTCODE',
 25: 'I-POSTCODE',
 26: 'B-PASS',
 27: 'I-PASS',
 28: 'I-COUNTRY',
 29: 'I-CITY',
 30: 'B-PASSPORT',
 31: 'I-PASSPORT',
 32: 'B-TEL',
 33: 'I-TEL',
 34: 'B-DRIVERLICENSE',
 35: 'I-DRIVERLICENSE',
 36: 'B-BOD',
 37: 'I-BOD',
 38: 'B-SEX',
 39: 'B-IP',
 40: 'I-IP',
 41: 'I-SEX',
 42: 'I-BUILDING',
 43: 'B-SECADDRESS',
 44: 'I-SECADDRESS',
 45: 'B-LASTNAME3',
 46: 'I-LASTNAME3',
 47: 'B-GIVENNAME1',
 48: 'I-GIVENNAME1',
 49: 'B-GIVENNAME2',
 50: 'I-GIVENNAME2',
 51: 'B-TITLE',
 52: 'I-TITLE',
 53: 'B-GEOCOORD',
 54: 'I-GEOCOORD',
 55: 'B-CARDISSUER',
 56: 'I-CARDISSUER'}

In [11]:
train_df = train_df.drop(columns='language')
valid_df = valid_df.drop(columns='language')

In [12]:
train_df.iloc[0]

source_text          Subject: Group Messaging for Admissions Proces...
target_text          Subject: Group Messaging for Admissions Proces...
privacy_mask         [{'value': 'wynqvrh053', 'start': 287, 'end': ...
span_labels          [[440, 453, "USERNAME"], [430, 437, "TIME"], [...
mbert_text_tokens    [Sub, ##ject, :, Group, Mess, ##aging, for, Ad...
mbert_bio_labels     [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...
id                                                              40767A
set                                                              train
Name: 0, dtype: object

In [13]:
from sklearn.metrics import classification_report
from transformers import BertTokenizer, BertForSequenceClassification

import torch
from torch.optim import Adam
from torch.utils.data import DataLoader, Dataset

In [14]:
# class BertDataset(Dataset):

#     def __init__(self, mbert_tokens_list,
#                 mbert_labels_list, label2id, max_len=128):
#         self.tokenizer = BertTokenizerFast.from_pretrained('bert-base-cased')
#         self.tokens_list = mbert_tokens_list
#         self.labels_list = mbert_labels_list
#         self.label2id = label2id
#         self.max_len = max_len

#     def __len__(self):
#         return len(self.tokens_list)

#     def __getitem__(self, idx):
#         tokens, labels = self.tokens_list[idx], self.labels_list[idx]

#         #Convert string BIO label to integer ID
#         label_ids = [self.label2id[label] for label in labels]

#         encoding = self.tokenizer(
#             tokens,
#             is_split_into_words=True,
#             padding='max_length',
#             truncation=True,
#             max_length=self.max_len,
#             return_tensors='pt'
#         )

#         seq_ids = encoding.word_ids(batch_index=0)
#         final_labels = []

#         label_idx = 0
#         for seq_id in seq_ids:
#             if seq_id is None:
#                 final_labels.append(-100)

#             else:
#                 if label_idx < len(label_ids):
#                     final_labels.append(label_ids[label_idx])
#                 else:
#                     final_labels.append(-100)
#         #Structure the dict output for huggingface model
#         item = {key: val.squeeze(0) for key, val in encoding.items()}
#         item['labels'] = torch.tensor(final_labels, dtype=torch.long)

#         return item

In [15]:
import torch
from torch.utils.data import Dataset
from transformers import BertTokenizerFast

class BertDataset(Dataset):

    def __init__(self, mbert_tokens_list, mbert_labels_list, label2id, max_len=128):
        # Make sure to use BertTokenizerFast so word_ids() works properly
        self.tokenizer = BertTokenizerFast.from_pretrained('bert-base-cased')
        self.tokens_list = mbert_tokens_list
        self.labels_list = mbert_labels_list
        self.label2id = label2id
        self.max_len = max_len

    def __len__(self):
        return len(self.tokens_list)

    def __getitem__(self, idx):
        tokens, labels = self.tokens_list[idx], self.labels_list[idx]

        # Convert string BIO label to integer ID
        label_ids = [self.label2id[label] for label in labels]

        encoding = self.tokenizer(
            tokens,
            is_split_into_words=True,
            padding='max_length',
            truncation=True,
            max_length=self.max_len,
            return_tensors='pt'
        )

        seq_ids = encoding.word_ids(batch_index=0)
        final_labels = []

        previous_word_idx = None
        for seq_id in seq_ids:
            # 1. Special tokens ([CLS], [SEP], [PAD]) get -100
            if seq_id is None:
                final_labels.append(-100)
            
            # 2. If it's the first subword token of a word, assign its true label
            elif seq_id != previous_word_idx:
                if seq_id < len(label_ids):
                    final_labels.append(label_ids[seq_id])
                else:
                    final_labels.append(-100)
                previous_word_idx = seq_id
                
            # 3. If it's a continuing subword piece (e.g., ##oh), set to -100 to ignore it
            else:
                final_labels.append(-100)

        # Structure the dict output for huggingface model
        item = {key: val.squeeze(0) for key, val in encoding.items()}
        item['labels'] = torch.tensor(final_labels, dtype=torch.long)

        return item

In [16]:
train_df.iloc[0]

source_text          Subject: Group Messaging for Admissions Proces...
target_text          Subject: Group Messaging for Admissions Proces...
privacy_mask         [{'value': 'wynqvrh053', 'start': 287, 'end': ...
span_labels          [[440, 453, "USERNAME"], [430, 437, "TIME"], [...
mbert_text_tokens    [Sub, ##ject, :, Group, Mess, ##aging, for, Ad...
mbert_bio_labels     [O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...
id                                                              40767A
set                                                              train
Name: 0, dtype: object

In [17]:
from transformers import BertTokenizerFast

In [18]:
train_dataset = BertDataset(mbert_tokens_list=train_df['mbert_text_tokens'],
                           mbert_labels_list=train_df['mbert_bio_labels'],
                           label2id=label2id)

train_loader = DataLoader(train_dataset, batch_size=128,
                         shuffle=True)

valid_dataset = BertDataset(mbert_tokens_list=valid_df['mbert_text_tokens'],
                           mbert_labels_list=valid_df['mbert_bio_labels'],
                           label2id=label2id)

valid_loader = DataLoader(valid_dataset, batch_size=128,
                         shuffle=True)

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

In [19]:
from transformers import BertForTokenClassification, get_linear_schedule_with_warmup
from torch.optim import AdamW

In [20]:
import matplotlib.pyplot as plt

In [21]:
len(train_dataset)

29908

In [22]:
model = BertForTokenClassification.from_pretrained(
    'bert-base-cased',
    num_labels=len(unique_labels),
    id2label=id2label,
    label2id=label2id
)

save_dir = "pii_mbert"

num_epochs = 10
optimizer = AdamW(model.parameters(),
                 lr=2e-5, weight_decay=0.01)
num_training_steps = len(train_loader) * num_epochs
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps = int(0.1*num_training_steps),
    num_training_steps=num_training_steps
)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(device)

model.train()
best_loss = float('inf')
epochs_no_improve = 0
n_epochs_stop = 2

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  436MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: bert-base-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [23]:
def train_one_epoch(model, loader):
    model.train()
    total = 0.0
    for batch in loader:
        optimizer.zero_grad()
        out = model(input_ids=batch["input_ids"].to(device),
                    attention_mask=batch["attention_mask"].to(device),
                    labels=batch["labels"].to(device))
        out.loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()
        total += out.loss.item()
    return total / len(loader)

@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    total = 0.0
    for batch in loader:
        out = model(input_ids=batch["input_ids"].to(device),
                    attention_mask=batch["attention_mask"].to(device),
                    labels=batch["labels"].to(device))
        total += out.loss.item()
    return total / len(loader)

best_val, no_improve = float("inf"), 0
for epoch in range(num_epochs):
    train_loss = train_one_epoch(model, train_loader)
    val_loss = evaluate(model, valid_loader)
    print(f"Epoch {epoch+1}: train {train_loss:.4f} | val {val_loss:.4f}")

    if val_loss < best_val:
        best_val, no_improve = val_loss, 0
        model.save_pretrained(save_dir)
        train_dataset.tokenizer.save_pretrained(save_dir)
    else:
        no_improve += 1
        if no_improve >= n_epochs_stop:
            print("Early stopping")
            break

Epoch 1: train 1.4556 | val 0.6306

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 2: train 0.5444 | val 0.4470

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 3: train 0.4388 | val 0.3973

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 4: train 0.3918 | val 0.3725

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 5: train 0.3645 | val 0.3613

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 6: train 0.3450 | val 0.3578

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 7: train 0.3301 | val 0.3503

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 8: train 0.3196 | val 0.3540
Epoch 9: train 0.3108 | val 0.3414

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch 10: train 0.3053 | val 0.3442